### ISSUE TITLE
`deoplete-padawan` doesn't send correct column number to `padawan`

### ISSUE THREAD

**Issue by cprn** [pbogut/deoplete-padawan#10] opened 2016-10-05 18:11 UTC
Continuation of the following:
https://github.com/mkusher/padawan.php/issues/67#issuecomment-251658235

> @mkusher, your right, prefix is not sent by the deoplete-padawan. The column is always set at the beginning of the word. [...]
> 
> @cprn, which version of padawan you are using? [...]
> 
> [...] It will work as expected with padawan from the master branch when I fix the issue @mkusher has addressed.

Version of `deoplete-padawan`:

> d74aad4dcfe0ce9e5f89b79f23ad92fa6b86d0d5 Update README.md

**Comment by pbogut** [comment] 2016-10-05 22:16
@cprn, you can try to use bugfix branch.

```
Plug 'pbogut/deoplete-padawan', { 'branch': 'bugfix/plain_function_completion' }
```

It's not finished yet but it should work (if you are using padawan.php from master branch) with minor issues, check #11 for details.

~~Ignore me, it's broken, need to spend more time on it.~~
It is broken but not because this PR.

**Comment by cprn** [comment] 2016-10-06 12:13
I read a mail and thought I'm using it wrong. :) Yeah, I agree, still broken unfortunately. I'm sorry I'm not more helpful, it actually stroke me in the middle of the project and we're on a deadline.

**Comment by pbogut** [comment] 2016-10-06 22:30
It's now fixed and merged to master.

@cprn, can you, please, check if it is working for you?

**Comment by cprn** [comment] 2016-10-07 01:23
Honestly, I don't know what I'm doing wrong but all I get now is:

```
Connection to padawan.php timed out
```

So I:
1. started `nvim` config from scratch,
2. upgraded `python` and `python3` providers
3. added `vim-plug`, `deoplete.nvim`, `padawan.vim` and `deoplete-padawan` (from `master`),
4. installed `mkusher/padawan` with `composer` globally.

No completion at all...

But I'm crashing so maybe I'm missing something obvious... I'll get back to it tomorrow with fresh head and edit this comment. Sorry. This is all I can give you straight away, didn't even start to analyze it yet, though:

```
[deoplete]   File "/home/mg/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 98, in gather_results
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete]   File "/home/mg/.config/nvim/plugged/deoplete-padawan/rplugin/python3/deoplete/sources/deoplete_padawan.py", line 94, in gather_candidates
[deoplete]     result = self.do_request('complete', params, contents)
[deoplete]   File "/home/mg/.config/nvim/plugged/deoplete-padawan/rplugin/python3/deoplete/sources/deoplete_padawan.py", line 140, in do_request
[deoplete]     return self.server.sendRequest(command, params, data)
[deoplete]   File "/home/mg/.config/nvim/plugged/deoplete-padawan/rplugin/python3/deoplete/sources/deoplete_padawan/padawan_server.py", line 56, in sendRequest
[deoplete]     timeout=3
[deoplete]   File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
[deoplete]     return opener.open(url, data, timeout)
[deoplete]   File "/usr/lib/python3.4/urllib/request.py", line 464, in open
[deoplete]     response = self._open(req, data)
[deoplete]   File "/usr/lib/python3.4/urllib/request.py", line 482, in _open
[deoplete]     '_open', req)
[deoplete]   File "/usr/lib/python3.4/urllib/request.py", line 442, in _call_chain
[deoplete]     result = func(*args)
[deoplete]   File "/usr/lib/python3.4/urllib/request.py", line 1211, in http_open
[deoplete]     return self.do_open(http.client.HTTPConnection, req)
[deoplete]   File "/usr/lib/python3.4/urllib/request.py", line 1186, in do_open
[deoplete]     r = h.getresponse()
[deoplete]   File "/usr/lib/python3.4/http/client.py", line 1227, in getresponse
[deoplete]     response.begin()
[deoplete]   File "/usr/lib/python3.4/http/client.py", line 386, in begin
[deoplete]     version, status, reason = self._read_status()
[deoplete]   File "/usr/lib/python3.4/http/client.py", line 348, in _read_status
[deoplete]     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
[deoplete]   File "/usr/lib/python3.4/socket.py", line 374, in readinto
[deoplete]     return self._sock.recv_into(b)
[deoplete] ConnectionResetError: [Errno 104] Connection reset by peer
[deoplete] Could not get completions from: padawan.  Use :messages for error details.
```

**Comment by pbogut** [comment] 2016-10-07 05:44
Can you also check padawan server log, please? 

EDIT:
If you updated padawan server from composer then you can try to generate the index for your project once again by `padawan generate`. Sometimes an index is not compatible after an update.

**Comment by cprn** [comment] 2016-10-07 16:59
I removed the `.padawan` directory to remove bias. Run `nvim`, opened a project file, run `:PadawanGenerateIndex` (it did), then started typing "is_array":

```
$ cat /tmp/padawan-server.log 
Started http server on 127.0.0.1:15155
POST /complete
[2016-10-07 18:56:37] completer.DEBUG: Cache status: active [] []
[2016-10-07 18:56:37] completer.INFO: Traversing with 1 processors [] []
[2016-10-07 18:56:37] completer.INFO: Found 0 nodes [] []
[2016-10-07 18:56:37] completer.DEBUG: Processing nodes 0 [] []
[2016-10-07 18:56:37] completer.DEBUG: Cache status: active [] []
[2016-10-07 18:56:37] completer.INFO: Traversing with 1 processors [] []
[2016-10-07 18:56:37] completer.INFO: Found 1 nodes [] []
[2016-10-07 18:56:37] completer.DEBUG: 0.023123025894165 seconds for ast processing [] []
[2016-10-07 18:56:37] completer.DEBUG: Found token 'i' with type 4097 [] []
[2016-10-07 18:56:37] completer.DEBUG: 0.025033950805664 seconds for entries generation [] []
Response time: 0.15166521072388
POST /complete
[2016-10-07 18:56:39] completer.DEBUG: 8.4877014160156E-5 seconds for ast processing [] []
[2016-10-07 18:56:39] completer.DEBUG: Found token 'i' with type 4097 [] []
[2016-10-07 18:56:39] completer.DEBUG: 0.0014529228210449 seconds for entries generation [] []
Response time: 0.0021510124206543
POST /complete
[2016-10-07 18:56:40] completer.DEBUG: 0.00010585784912109 seconds for ast processing [] []
[2016-10-07 18:56:40] completer.DEBUG: Found token 'i' with type 4097 [] []
[2016-10-07 18:56:40] completer.DEBUG: 0.0016679763793945 seconds for entries generation [] []
Response time: 0.0023610591888428
POST /complete
[2016-10-07 18:56:41] completer.DEBUG: 7.7009201049805E-5 seconds for ast processing [] []
[2016-10-07 18:56:41] completer.DEBUG: Found token 'i' with type 4097 [] []
[2016-10-07 18:56:41] completer.DEBUG: 0.0012199878692627 seconds for entries generation [] []
Response time: 0.0017099380493164
POST /complete
[2016-10-07 18:56:41] completer.DEBUG: 0.00012493133544922 seconds for ast processing [] []
[2016-10-07 18:56:41] completer.DEBUG: Found token 'i' with type 4097 [] []
[2016-10-07 18:56:41] completer.DEBUG: 0.0016829967498779 seconds for entries generation [] []
Response time: 0.0023560523986816
POST /complete
[2016-10-07 18:56:42] completer.DEBUG: 0.00010800361633301 seconds for ast processing [] []
[2016-10-07 18:56:42] completer.DEBUG: Found token 'i' with type 4097 [] []
[2016-10-07 18:56:42] completer.DEBUG: 0.0017688274383545 seconds for entries generation [] []
Response time: 0.002479076385498
POST /complete
[2016-10-07 18:56:43] completer.DEBUG: 0.00010204315185547 seconds for ast processing [] []
[2016-10-07 18:56:43] completer.DEBUG: Found token 'i' with type 4097 [] []
[2016-10-07 18:56:43] completer.DEBUG: 0.0016529560089111 seconds for entries generation [] []
Response time: 0.0022380352020264
POST /complete
[2016-10-07 18:56:44] completer.DEBUG: 0.00012493133544922 seconds for ast processing [] []
[2016-10-07 18:56:44] completer.DEBUG: Found token 'i' with type 4097 [] []
[2016-10-07 18:56:44] completer.DEBUG: 0.0017910003662109 seconds for entries generation [] []
Response time: 0.0025391578674316
```

Then I started to type `$x = new Foob` and got the same `rplugin` errors as before. Called `:UpdateRemotePlugins` and they stopped, autocompletion got working again for my custom classes but still not for built-ins (same log as in this comment, only first letter is sent as token). After restarting `nvim` I got the same `rplugin` errors again.

Can't really put my finger on it but something's not right at all and if it only happens at my end then I'm stuck. Removed everything from the beginning and reinstalled it again with no success.

**Comment by pbogut** [comment] 2016-10-07 20:00
I've checked it on another machine and it is working all right. I can't reproduce your error :(

When I'm using padawan 0.2.1
`"mkusher/padawan": "^0.2.1"` then I have no built in suggestions like you as this version does not provide it.
When I'm using master one
`"mkusher/padawan": "dev-master@dev"`
I have completion for built-in functions.

Both times I have no error with the connection. I'm using python3.5, though, maybe that's the problem but `ConnectionResetError: [Errno 104] Connection reset by peer` would suggest that padawan server crashed, can you check padawan-server output when the plugin is crashing, please?

@mkusher, sorry for bothering you, but  maybe you have idea what can cause the problem?

**Comment by cprn** [comment] 2016-10-07 20:11
I'm using `php5.6` + `python3.4` at work but `php7` + `python3.5` at home.

Reinstalled at home and no errors regarding `rplugin` so that was an involuntary misdirection, sorry.
I temporarily have a problem installing `mkusher/padawan: "dev-master@dev"` because of some dependency issue (`react/http: "dev-master"` throws errors).

Forget about it for a day or two, I'll get back to you when I know what's causing it. I hate to be the problem here.

When I try to complete the built-in on `mkusher/padawan: "^0.2.1"` the logs look like described in previous comment , i.e. there's only an `f` tag in logs over and over when I try to type `foreach`. So I'm guessing this is the lack of the feature in this version, like you said. The fact logs don't mention the whole key pattern progression (`f` then `fo` then `for` as I type) threw me off.

**Comment by mkusher** [comment] 2016-10-07 20:39
I guess the problem is with padawan.php installation... The simplest way is to completely remove it `composer global remove mkusher/padawan`, update minimum stability and then install dev-master version.
Need to think more about providing simpler way of managing padawan.php installation

btw @pbogut I've subscribed to all updates in your repo ;)

**Comment by mkusher** [comment] 2016-10-07 20:42
And one more tip: you can easily check padawan's version by `padawan --version`

**Comment by pbogut** [comment] 2016-10-08 09:10
@cprn 

> The fact logs don't mention the whole key pattern progression (f then fo then for as I type) threw me off.

That's by design, deoplete.nvim is handling the filtration, so there is no reason te send anything else to padawan server. I could change it but I see no point in doing it.

**Closed as completed** 2016-11-05 08:34 UTC
Labels: bug
